HANDLER_TYPE_CSV = "csv"
HANDLER_TYPE_MONGO = "mongodb"
HANDLER_TYPE_AVRO = "avro"
HANDLER_TYPE_PARQUET = "parquet"
HANDLER_TYPE_S3 = "s3"
HANDLER_TYPE_POSTGRES = "postgres"

# Supported file-based source types
FILE_BASED_TYPES = {HANDLER_TYPE_CSV, HANDLER_TYPE_AVRO, HANDLER_TYPE_PARQUET}

# All supported source types
SUPPORTED_TYPES = {
    HANDLER_TYPE_CSV, 
    HANDLER_TYPE_MONGO, 
    HANDLER_TYPE_AVRO, 
    HANDLER_TYPE_PARQUET, 
    HANDLER_TYPE_S3,
    HANDLER_TYPE_POSTGRES
}